FROM node:16-alpine
RUN apk --no-cache add git
WORKDIR /source/rp
COPY ./rp_server ./rp_server
COPY ./lib ./lib
WORKDIR /source/rp/rp_server
RUN npm install --only=production


ENV NODE_PATH=/source/rp/rp_server/node_modules
ENV PORT=80
ENV LOG_LEVEL=info
EXPOSE 80
CMD ["sh", "-c", "node rp_server.js"]
