version: '3.7'
x-LOG_LEVEL    : &LOG_LEVEL LOG_LEVEL=info
x-NODE_ENV     : &NODE_ENV NODE_ENV=production
x-DATABASE_URL : &DATABASE_URL DATABASE_URL=mongodb://172.18.100.8:27017
x-PREFIX       : &PREFIX PREFIX=rp
services:
  sioserver:
    container_name: "sioserver" 
    # build:
    #   context: ..
    #   dockerfile: sioserver.Dockerfile    
    image: ucipass/sioserver
    environment: 
      - *LOG_LEVEL
      - *NODE_ENV
      - *DATABASE_URL
      - *PREFIX
      # - DATABASE_PASSWORD=admin
      # - DATABASE_USERNAME=admin
      # - PORT=8081      
      # - VUE_APP_PREFIX=rp
      # - VUE_APP_SERVER_PORT=8080
    command: node sioserver/sio-server.js
    ports: 
      - 8081:8081
    links: 
      - mongodb 
    depends_on: 
      - mongodb       
  manager:
    container_name: "manager" 
    # build:
    #   context: .
    #   dockerfile: sioserver.Dockerfile    
    image: ucipass/manager
    environment:
      - *LOG_LEVEL
      - *NODE_ENV
      - *DATABASE_URL
      - *PREFIX
      - SECRET_KEY=MySuperSecretKey #Change this for production
      - MANAGER_PORT=8080      
      - URL_SIO_STATUS=http://sioserver:8081/status
      - URL_SIO_REFRESH=http://sioserver:8081/refresh
      #- DATABASE_USERNAME=admin
      #- DATABASE_PASSWORD=admin
      #- VUE_APP_PREFIX=rp
      #- VUE_APP_SERVER_PORT=8080
      #- DATABASE_URL=mongodb://172.18.100.8:27017
    command: node manager/index.js
    # command: sh -c "sleep 6000"
    ports: 
      - 8080:8080
    links: 
      - mongodb 
    depends_on: 
      - mongodb 
  mongodb: 
    container_name: "mongodb" 
    image: mongo:latest 
    volumes: 
      - /tmp/db:/data/db 
    ports: 
      - 27017:27017 
    command: --logpath /dev/null
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin 
      - MONGO_INITDB_ROOT_PASSWORD=admin