version: '3'
services:
  sioserver:
    container_name: "sioserver" 
    # build:
    #   context: ..
    #   dockerfile: sioserver.Dockerfile    
    image: ucipass/sioserver
    environment:
      - LOG_LEVEL=info
      # - PREFIX=rp
      - PORT=8081      
      - NODE_ENV=production
      # - VUE_APP_PREFIX=rp
      - VUE_APP_SERVER_PORT=8080
      # - DATABASE_URL=mongodb://172.18.100.8:27017
      - DATABASE_URL=mongodb://mongodb:27017
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
      - SECRET_KEY=MySuperSecretKey
    command: node sioserver/sio-server.js
    ports: 
      - 8081:8081
    links: 
      - mongodb 
    depends_on: 
      - mongodb       
  manager:
    container_name: "manager" 
    # build:
    #   context: ..
    #   dockerfile: sioserver.Dockerfile    
    image: ucipass/manager
    environment:
      - LOG_LEVEL=info
      # - MANAGER_PREFIX=rp
      - MANAGER_PORT=8080      
      - NODE_ENV=production
      # - VUE_APP_PREFIX=rp
      - VUE_APP_SERVER_PORT=8080
      # - DATABASE_URL=mongodb://172.18.100.8:27017
      - DATABASE_URL=mongodb://mongodb:27017
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
      - SECRET_KEY=MySuperSecretKey
    command: node manager/index.js
    # command: sh -c "sleep 6000"
    ports: 
      - 8080:8080
    links: 
      - mongodb 
    depends_on: 
      - mongodb 
  mongodb: 
    container_name: "mongodb" 
    image: mongo:latest 
    volumes: 
      - /tmp/db:/data/db 
    ports: 
      - 27017:27017 
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin 
      - MONGO_INITDB_ROOT_PASSWORD=admin