FROM node:14-alpine

WORKDIR /source/rp
COPY ./rp_server ./rp_server
COPY ./lib ./lib
WORKDIR /source/rp/rp_server
RUN npm install
# RUN npm run client_win  --only=production
# RUN npm run client_lin  --only=production
# RUN npm run client_mac  --only=production

# DELETE EVERYTHING EXCEPT dist to save space
# RUN ls | grep -v dist | xargs rm -rf 

CMD ["sh", "-c", "node rp_server.js"]
#CMD ["sh", "-c", "sleep 6000"]