# build stage
FROM node:12-alpine as build-stage
RUN apk add --no-cache python2 make g++
# RUN apk add --no-cache python3 py3-pip make g++
WORKDIR /app
COPY ./rp_frontend ./rp_frontend
WORKDIR /app/rp_frontend
RUN npm install
RUN npm run build

# production stage
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/rp_frontend/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

