version: '3'
services:
  manager:
    container_name: "sioserver" 
    build:
      context: ..
      dockerfile: sioserver.Dockerfile
    image: ucipass/sioserver
    environment:
      - NODE_ENV=production
      - MANAGER_PREFIX=rp
      - MANAGER_PORT=3000
      - DATABASE_URL=mongodb://mongodb2:27017/rp
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
      - SECRET_KEY=MySuperSecretKey
    # command: node server.js
    ports: 
      - 8081:8081
    links: 
      - mongodb2
    depends_on: 
      - mongodb2
  mongodb2: 
    container_name: "mongodb2" 
    image: mongo:latest 
    # volumes: 
    #   - /tmp/db:/data/db 
    # ports: 
    #   - 27017:27017 
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin 
      - MONGO_INITDB_ROOT_PASSWORD=admin      
