on: push
name: npm build, lint, test and publish
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x 
    - name: Start Mongodb container for testing
      run: docker run -d -p27017:27017 --restart unless-stopped -v /mongodb:/data/db -e MONGO_INITDB_ROOT_USERNAME=admin -e MONGO_INITDB_ROOT_PASSWORD=admin --name mongodb  mongo 
    - name: Install Dependencies
      run: npm install 
    - name: Run testing scripts
      run: npm run testmongodb
    - run: npm run testmanager
    - run: npm run testsioserver
    - name: Docker Login
      - run: npm run testmongo
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Docker Build & Publish Manager
      run: docker build -f manager.Dockerfile -t ucipass/manager .
    - run: docker push ucipass/manager
    - name: Docker Build & Publish Socket.IO Server
      run: docker build -f sioserver.Dockerfile -t ucipass/sioserver .
    - run: docker push ucipass/sioserver
